module.exports = {
  male: {
    file: '场景2.png', label: '场景2（球场举旗）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    refNormalize: true,
    validateHeadSwap: true,
    validationTarget: 'the main swapped person behind the flag',
    validationRule: 'The head must be centered above the neck behind the flag. The flag letters and Bayern jersey must be completely preserved.',
    mask: {
      cx: 360, cy: 168, w: 162, h: 248,
      apiCx: 360, apiCy: 150, apiW: 128, apiH: 244,
      compCx: 360, compCy: 168, compW: 162, compH: 248,
      compSolidTopH: 68,
    },
  },
  female: {
    file: '场景2.png', label: '场景2（球场举旗）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    refScale: 0.26, refAnchor: 'north', refOffsetY: 0.05,
    refNormalize: true,
    validateHeadSwap: true,
    validationTarget: 'the main swapped person behind the flag',
    validationRule: 'The female head must be compact and not oversized. Full crown visible. Flag letters preserved. Right ear and side hair preserved.',
    extraPromptLines: [
      'Flag portrait fit: Keep the inserted female head compact, upright, and centered above the neck opening behind the flag.',
      'Female head scale: Keep the female head modest and slightly smaller than the placeholder width. Do NOT enlarge the face to fill the whole replacement box.',
      'Head proportion lock: Keep the head clearly narrower than the shoulder span and smaller than the full replacement region. Gain crown room by leaving more air above the hair, NOT by enlarging the whole head.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis. Do NOT slide the head left, right, or downward.',
      'Vertical lock: Keep the eyes in the upper-middle of the replacement area and keep the chin clearly above the top edge of the flag.',
      'Crown clearance: Leave visible breathing room above the crown so the full hair silhouette stays inside the replacement area.',
      'Hairstyle source lock: Reproduce the exact hairstyle structure from Image 2, including parting direction, fringe or no-fringe status, top-hair volume, and whether the hair is worn down or tied up.',
      'Bang rule: If Image 2 shows an exposed forehead or no bangs, do NOT invent bangs, curtain fringe, or a new front fringe.',
      'Hair state lock: If Image 2 shows the hair worn down, keep it worn down. Do NOT convert loose hair into a bun, ponytail, tied-up updo, or a generic celebrity-style hairstyle.',
      'Close-selfie handling: If Image 2 is a close selfie or partially framed photo, infer one complete natural head from the visible identity cues only. Do NOT paste a literal photo crop, room patch, or selfie rectangle into Image 1.',
      'Full-head completion: Even when Image 2 is tightly framed, output one complete photorealistic head from crown to chin above the flag. Do NOT output only the upper half of the source face.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no 3D avatar, and no doll-like stylization.',
      'Jersey preservation: Preserve the original Bayern shirt collar, shoulder seams, sleeve openings, and chest area from Image 1. Replace only the head and natural neck transition above the shirt.',
      'Shoulder protection: Do NOT redesign the shirt neckline, shoulder cutouts, sleeve shape, or jersey fabric around the collarbone area.',
      'Long-hair routing: If Image 2 has medium or long hair, let the longer side hair continue beside the face and then fall behind the shoulders or behind the flag. Do NOT let a flat hair curtain cover the front flag letters.',
      'Right-ear visibility: Preserve the full viewer-right ear when it exists in Image 2. Do NOT hide, crop, or blur away the viewer-right ear.',
      'Hair silhouette: Preserve the outer hair contour on the viewer-right side of the head. Do NOT blur away or trim the loose side hair near the ear and shoulder.',
      'Maximum head size: The head width must NOT exceed the original placeholder width. If the reference face appears large, scale it DOWN to fit naturally — a slightly small head is better than an oversized one.',
      'Right-side coverage: Fully include the viewer-right temple, ear, side hair, and the adjacent outer hair contour inside the replacement area.',
      'Patch suppression: The replacement area must contain only the head, hair, ears, and natural neck transition. Do NOT expose any source-photo wall, ceiling, room corner, or rectangular background patch.',
      'Background lock: Do NOT bring any source-photo wall, ID-photo backdrop, or indoor background into Image 1.',
    ],
    extraNegativeTerms: [
      'oversized female head', 'giant face', 'large head small body', 'zoomed-in face',
      'off-center head', 'shifted head', 'head too low', 'head too high',
      'cropped crown', 'top-clipped hair', 'cut-off forehead',
      'invented bangs', 'added fringe', 'curtain bangs not in source', 'generic idol fringe',
      'tied-up hair from loose-hair source', 'ponytail from down hair', 'bun from loose hair', 'updo not in source',
      'cartoon avatar', '3d avatar', 'pixar face', 'emoji face', 'doll face', 'cgi face',
      'missing right ear', 'cropped right ear', 'blurred right ear',
      'missing right-side hair', 'trimmed side hair', 'hair cut off at right edge',
      'literal selfie crop', 'photo rectangle pasted into scene', 'source image patch', 'partial selfie patch', 'source room rectangle',
      'upper-half face only', 'forehead-only face', 'incomplete lower face from source crop',
      'face inside flag', 'chin inside flag', 'portrait sunk too low',
      'hair curtain over flag', 'hair covering flag letters', 'front-draped long hair over shirt',
      'altered jersey collar', 'changed shoulder cutout', 'redesigned shirt neckline', 'shirt turned into skin', 'wrong jersey shape',
      'source photo corner', 'room corner patch', 'ceiling patch',
      'source photo background', 'id photo background', 'indoor wall patch',
      'visible square crop edge', 'rectangular patch edge',
    ],
    mask: {
      cx: 360, cy: 148, w: 142, h: 246,
      apiCx: 394, apiCy: 124, apiW: 176, apiH: 222,
      apiShape: 'hairDome',
      apiDomeH: 104,
      apiDomeExpandX: 14,
      apiSideHairW: 24,
      apiSideHairH: 58,
      apiSideHairOffsetX: 78,
      apiSideHairOffsetY: 132,
      compCx: 396, compCy: 136, compW: 198, compH: 246,
      compShape: 'hairDome',
      compDomeH: 116,
      compDomeExpandX: 18,
      compSideHairW: 28,
      compSideHairH: 70,
      compSideHairOffsetX: 84,
      compSideHairOffsetY: 146,
      compFeather: 10,
    },
  },
};
