module.exports = {
  male: {
    file: '场景4男.png', label: '场景4男（啤酒节，替换最左）',
    mode: 'inpaint', size: '2326x1588', guidance: 8,
    apiMaskScale: 1.0,
    // v1.7: 切回 inpaint 模式，faceswap-composite 模式会导致男性发型女性化（波波头+齐刘海）
    strength: 0.45,
    templateType: 'faceswap',
    targetPerson: 'the person on the far left',
    refScale: 0.45, refAnchor: 'north', refOffsetY: 0.08,
    refCrop: { width: 0.72, height: 0.78, offsetX: 0.5, offsetY: 0.00 },
    refNormalize: true,
    skipComposite: false, // 必须 composite：把原始底图 mask 外像素贴回，锁定背景
    validateHeadSwap: true,
    validationTarget: 'the person on the far left',
    validationRule: 'The male hairstyle MUST match the source photo — buzz cut stays buzz cut, short hair stays short. No feminine bob or pixie cut. Complete head from crown to chin. Bavarian outfit preserved. No source clothing visible.',
    extraPromptLines: [
      'Hairstyle source lock (HIGHEST PRIORITY): Reproduce the EXACT hairstyle from Image 2 — same length, same texture, same volume, same parting direction. Do NOT invent or change the hairstyle.',
      'Short-hair fidelity: If Image 2 shows very short hair (buzz cut, crew cut, fade), the result MUST also show very short hair. Do NOT add length or volume that does not exist in Image 2.',
      'Anti-feminization lock (MANDATORY): If the person in Image 2 is male with a short masculine hairstyle (buzz cut, crew cut, fade, short back-and-sides), the result MUST show that EXACT same short masculine hairstyle. Do NOT convert it to a feminine bob, pixie cut, soft layers, or any longer hairstyle. SHORT MALE HAIR STAYS SHORT MALE HAIR.',
      'Hair length copy: Match the hair length precisely. Short stays short, medium stays medium. Do NOT lengthen or shorten the hair from Image 2.',
      'Hair texture copy: Match the hair texture from Image 2 — straight, wavy, curly, spiky, or slicked. Do NOT change the texture.',
      'Crown clearance: Leave visible breathing room above the crown so the full hair silhouette stays visible. Do NOT clip the top of the hair.',
      'Head proportion: Keep the head proportional to the shoulders. Do NOT enlarge the head.',
      'Scene clothing preservation (CRITICAL): Keep the ORIGINAL Bavarian outfit from Image 1 — the gray jacket, maroon vest, and white shirt. Do NOT render any collar, shirt, jacket, or clothing from Image 2 inside the replacement area. The mask covers ONLY the head and natural neck above the collar.',
      'Source clothing exclusion: Explicitly ignore any clothing visible in Image 2. Render ONLY bare neck skin below the chin, transitioning into the existing collar of Image 1. Do NOT paint the user shirt collar or jacket into the scene.',
      'Neck-clothing boundary (CRITICAL): Stop ALL AI rendering at the collar neckline. Below the chin, render ONLY smooth neck skin that transitions directly into the EXISTING collar from Image 1. The user\'s original clothing, collar, shirt neckline, and ANY fabric from Image 2 must NOT appear in the result.',
      'Single-head rule: Keep only one face aligned to the placeholder neck.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'bob cut from short hair', 'long hair from buzz cut',
      'feminine bob from male source', 'pixie cut from male source', 'soft layered hair from male',
      'feminized male hair', 'gender swapped hairstyle', 'woman hairstyle on male face',
      'different hairstyle', 'changed hair texture',
      'cropped crown', 'top-clipped hair',
      'oversized head', 'source photo clothing',
      'user collar visible', 'reference shirt collar', 'wrong collar color',
      'source jacket', 'reference jacket sleeves',
      'collar bleeding', 'reference collar overlap', 'user neckline fabric',
      'double face', 'residual mannequin head',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
    ],
    // mask 坐标基于新底图 (1005x686)，v6: mask 上移收缩避免领口溢出
    mask: {
      cx: 142, cy: 234, w: 116, h: 186,
      apiCx: 144, apiCy: 228, apiW: 118, apiH: 178,
      apiShape: 'hairDome',
      apiDomeH: 70,
      apiDomeExpandX: 12,
      apiSideHairW: 16,
      apiSideHairH: 42,
      apiSideHairOffsetX: 50,
      apiSideHairOffsetY: 82,
      compCx: 144, compCy: 230, compW: 148, compH: 198,
      compShape: 'hairDome',
      compDomeH: 82,
      compDomeExpandX: 16,
      compSideHairW: 22,
      compSideHairH: 54,
      compSideHairOffsetX: 58,
      compSideHairOffsetY: 90,
      compFeather: 18,
    },
  },
  female: {
    file: '场景4女.png', label: '场景4女（啤酒节，替换最左）',
    mode: 'inpaint', size: '2328x1586', guidance: 8,
    apiMaskScale: 0.88, checkHeadSize: true,
    strength: 0.55,
    templateType: 'faceswap',
    targetPerson: 'the person on the far left',
    refScale: 0.18, refAnchor: 'north', refOffsetY: 0.06,
    refCrop: { width: 0.74, height: 0.82, offsetX: 0.5, offsetY: 0.0 },
    refNormalize: true,
    refNormalizeCenterOnly: true,
    refNormalizeMinFaceWidth: 18,
    refNormalizeMinFaceHeight: 18,
    refNormalizeMinFaceArea: 500,
    refNormalizeMaxCropWidth: 0.82,
    refNormalizeMaxCropHeight: 0.86,
    refHeadFillRatio: 0.17,
    skipComposite: false,
    validateHeadSwap: true,
    validationTarget: 'the person on the far left',
    validationRule: 'The female head must remain the exact same person as Image 2 and preserve the exact hairstyle from Image 2, including fringe or no-fringe status, loose vs tied state, and overall hair silhouette. The female head must have full crown and hair visible, remain compact, and not look oversized. The original Bavarian dirndl neckline, collar seam, shoulder line, and chest area from Image 1 must remain unchanged. No clipped hair top. No altered collar. No source clothing visible.',
    extraPromptLines: [
      'Hairstyle source lock (HIGHEST PRIORITY): Reproduce the EXACT hairstyle from Image 2 — same length, same texture, same volume, same parting direction. Do NOT invent or change the hairstyle.',
      'Hair length copy: Match the hair length precisely. Short stays short, medium stays medium, long stays long. Do NOT lengthen or shorten the hair from Image 2.',
      'Hair texture copy: Match the hair texture from Image 2 — straight, wavy, curly, or tied up. Do NOT change the texture.',
      'Crown clearance: Leave visible breathing room above the crown for the full hair silhouette. Do NOT clip or cut off the top of the hair.',
      'Full hair rendering: Render the COMPLETE hairstyle from Image 2 including the full length, volume, and natural fall of the hair. If the person has long hair, the full length must be visible, falling naturally past the shoulders. Do NOT crop, truncate, or cut off any part of the hair.',
      'Festival portrait fit: Keep the inserted female head compact, upright, and centered above the neck in the group photo.',
      'Female head scale: Keep the female head modest and proportional. Do NOT enlarge the face to fill the whole replacement box.',
      'Head proportion lock: Keep the head compact and clearly proportional to the group. Leave more breathing room above the crown instead of enlarging the entire head.',
      'Identity lock: Keep the exact same female identity from Image 2. Do NOT beautify, slim the face, enlarge the eyes, narrow the nose, or turn the person into a generic model-like face.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis.',
      'Visible neck lock: Leave a short but clearly visible front neck section below the chin. Do NOT let the jaw melt directly into the dress neckline.',
      'Neck width lock: Keep the lower neck narrow and centered. Do NOT expand the replacement area across the upper chest or shoulder line.',
      'Dirndl neckline preservation: Keep the exact neckline curve, lace edge, collar seam, and chest fabric from Image 1 unchanged. Do NOT repaint the neckline or upper chest.',
      'Upper-body stop line: The generated region must stop above the dirndl neckline. Do NOT generate clothing, skin, or hair over the upper chest panel.',
      'Long-hair routing: If Image 2 has long hair, let side hair fall naturally behind the shoulders and onto the upper back. Ensure both sides of the hair are fully rendered and visible.',
      'Scene clothing preservation (CRITICAL): Keep the ORIGINAL Bavarian dirndl outfit from Image 1. Do NOT render any collar, shirt, or clothing from Image 2 inside the replacement area. The mask covers ONLY the head and natural neck above the collar.',
      'Source clothing exclusion: Explicitly ignore any clothing visible in Image 2. Render ONLY bare neck skin below the chin, transitioning into the existing collar of Image 1. Do NOT paint the user top or collar into the scene.',
      'Neck-clothing boundary (CRITICAL): Stop ALL AI rendering at the collar neckline. Below the chin, render ONLY smooth neck skin that transitions directly into the EXISTING collar from Image 1. The user\'s original clothing, collar, and ANY fabric from Image 2 must NOT appear in the result.',
      'Skin tone continuity: The face and neck skin tone must dissolve smoothly into the original body with no hard cutoff, rectangle edge, or color jump at the neck base.',
      'Single-head rule: Keep only one face aligned to the placeholder neck.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'identity drift', 'different person', 'generic model face', 'beautified face', 'face slimmed from source', 'changed jawline', 'changed nose shape',
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'bob cut from short hair', 'long hair from short hair source',
      'different hairstyle', 'changed hair texture',
      'cropped crown', 'top-clipped hair', 'truncated hair', 'hair cut off',
      'incomplete hair', 'half hair', 'shortened long hair',
      'missing chin', 'blank mannequin neck',
      'double face', 'residual mannequin head',
      'oversized head',
      'wide neck', 'thick neck block', 'boxy neck base',
      'source photo clothing', 'user collar visible',
      'reference shirt collar', 'wrong collar color',
      'source top', 'reference clothing fabric',
      'source photo background',
      'collar bleeding', 'reference collar overlap', 'user neckline fabric',
      'hard neck edge', 'neck cut line', 'neck color seam', 'chest repaint', 'altered dirndl neckline', 'wrong neckline curve', 'changed lace collar', 'upper chest repaint',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
    ],
    // mask 坐标基于新底图 (1004x684)
    // v8: 维持底图锁定，但最终贴回不再使用大矩形 body；
    // 只保留更大的头发区域 + 更窄的颈部过渡，解决头大、颈部分割线、头发消失
    mask: {
      cx: 170, cy: 220, w: 104, h: 172,
      apiCx: 170, apiCy: 200, apiW: 84, apiH: 138,
      apiShape: 'hairDome',
      apiDomeH: 110,
      apiDomeExpandX: 12,
      apiSideHairW: 32,
      apiSideHairH: 92,
      apiSideHairOffsetX: 52,
      apiSideHairOffsetY: 82,
      apiNoBodyRect: true,
      apiNeckRx: 9,
      apiNeckRy: 9,
      apiNeckOffsetY: 144,
      apiMaxBottomY: 276,
      compCx: 170, compCy: 215, compW: 214, compH: 270,
      compShape: 'hairDome',
      compDomeH: 175,
      compDomeExpandX: 14,
      compSideHairW: 38,
      compSideHairH: 120,
      compSideHairOffsetX: 58,
      compSideHairOffsetY: 102,
      compNoBodyRect: true,
      compNeckRx: 11,
      compNeckRy: 11,
      compNeckOffsetY: 220,
      compMaxBottomY: 360,
      compFeather: 16,
    },
  },
};
