module.exports = {
  male: {
    file: '场景1男.jpg', label: '场景1男（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    strength: 0.85,
    controlProfile: 'scene1_portrait',
    refScale: 0.34, refAnchor: 'north', refOffsetY: 0.08,
    refScaleCandidates: [0.34, 0.40],
    includeOriginalReferenceFallback: true,
    validateHeadSwap: true,
    preFillMask: true,
    refNormalize: true,
    extraPromptLines: [
      'Strict head size: The generated head MUST be small relative to the white mask area. The head width should be roughly half the mask width, and the head height about 60% of the mask height. Do NOT enlarge the head to fill the mask.',
      'Compact portrait fit: Keep the inserted head compact and upright, noticeably smaller than the full replacement box so the full crown, temples, and jawline stay well inside the edges with visible breathing room.',
      'Crown clearance: Leave generous breathing room above the crown. The full hair volume from roots to tips must be visible, including any hair that extends to the sides or upward. Do NOT clip any hair against the mask edge.',
      'Hair side coverage: Ensure hair on BOTH the left and right sides of the head is fully visible and not cut off. The mask is intentionally oversized to accommodate side hair and hair volume.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'No mannequin carry-over: Do NOT leave any mannequin skin or blank texture around the chin or neck base.',
      'Single-head rule: Keep only one face aligned to the placeholder neck.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic, not blurry or airbrushed.',
      'Neck skin tone continuity: Generate the neck with a SINGLE consistent skin tone from chin all the way down to the jersey collar, MATCHING the body skin tone visible at the collar and shoulder area. Do NOT create any visible color change line, two-tone effect, or skin tone boundary on the neck.',
      'Neck depth coverage: Generate realistic neck skin reaching deep into the collar opening area. The AI-generated neck must seamlessly meet the body skin with no exposed transition seam.',
      'Head proportion constraint: The head-to-shoulder width ratio must be approximately 1:1.7. The head MUST look proportionally small on the broad-shouldered athletic body. Do NOT make the head wider than about 55-60% of the shoulder width.',
      'Background consistency: Keep the locker background unchanged and blend the outer head edge softly.',
      'Hairstyle source lock: Reproduce the EXACT hairstyle from Image 2 — same length, same texture, same volume, same parting direction. Do NOT invent or change the hairstyle.',
      'Short-hair fidelity: If Image 2 shows very short hair (buzz cut, crew cut, fade), the result MUST also show very short hair. Do NOT add length or volume.',
      'Bang rule: If Image 2 shows no bangs, do NOT invent bangs or curtain fringe.',
      'Close-selfie handling: If Image 2 is a close selfie, infer one complete natural head from visible cues only. Do NOT paste a literal selfie rectangle.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'half face', 'cropped crown', 'top-clipped hair', 'clipped hair top',
      'side-clipped hair', 'hair cut off at edge', 'hair touching mask boundary',
      'double face', 'residual mannequin head',
      'missing chin', 'blank mannequin neck',
      'blurry neck', 'foggy neck edge',
      'dark head hole', 'black face void',
      'neck color seam', 'two-tone neck', 'neck skin tone jump', 'visible neck boundary line',
      'oversized head', 'giant head', 'head filling mask', 'head overflowing replacement area',
      'enlarged head', 'swollen face', 'head too big for frame', 'head touching mask edge',
      'wide head', 'broad face', 'head wider than shoulders',
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'different hairstyle', 'changed hair texture',
      'invented bangs', 'curtain bangs not in source',
      'bob cut from short hair', 'long hair from buzz cut',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
    ],
    mask: {
      cx: 1140, cy: 844, w: 136, h: 230,
      apiCx: 1142, apiCy: 812, apiW: 108, apiH: 226,
      apiShape: 'hairDome',
      apiDomeH: 126,
      apiDomeExpandX: 10,
      apiSideHairW: 16,
      apiSideHairH: 52,
      apiSideHairOffsetX: 56,
      apiSideHairOffsetY: 112,
      apiNeckRx: 66,
      apiNeckRy: 144,
      apiNeckOffsetY: 200,
      compCx: 1142, compCy: 814, compW: 160, compH: 318,
      compShape: 'hairDome',
      compDomeH: 152,
      compDomeExpandX: 26,
      compSideHairW: 28,
      compSideHairH: 68,
      compSideHairOffsetX: 74,
      compSideHairOffsetY: 128,
      compNeckRx: 100,
      compNeckRy: 188,
      compNeckOffsetY: 218,
      compFeather: 30,
    },
  },
  female: {
    file: '场景1女.jpg', label: '场景1女（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    strength: 0.85,
    controlProfile: 'scene1_portrait',
    refScale: 0.30, refAnchor: 'north', refOffsetY: 0.08,
    refScaleCandidates: [0.30, 0.36],
    refAlwaysSoftOval: true,
    validateHeadSwap: true,
    preFillMask: true,
    refNormalize: true,
    validationTarget: 'the main swapped person in the locker room',
    validationRule: 'The female head must be compact with full crown and hairstyle visible. No invented bangs. No mannequin residue. The Bayern jersey must be preserved.',
    extraPromptLines: [
      'Strict head size: The generated female head MUST be small relative to the white mask area. The head width should be roughly half the mask width. Do NOT enlarge the head to fill the mask.',
      'Compact portrait fit: Keep the inserted female head compact and upright, noticeably smaller than the full replacement box so the full crown and jawline stay well inside the edges.',
      'Crown clearance: Leave generous breathing room above the crown so the full hair silhouette, including any side hair, stays inside the replacement area.',
      'Hair side coverage: Ensure hair on BOTH the left and right sides of the head is fully visible and not cut off.',
      'Head proportion constraint: The head MUST look proportionally small on the body. Do NOT make the head wider than about 55-60% of the shoulder width.',
      'Hairstyle source lock: Reproduce the exact hairstyle structure from Image 2, including parting direction, fringe status, and whether hair is worn down or tied up.',
      'Bang rule: If Image 2 shows no bangs, do NOT invent bangs or curtain fringe.',
      'Close-selfie handling: If Image 2 is a close selfie, infer one complete natural head from visible cues only. Do NOT paste a literal selfie rectangle.',
      'Long-hair routing: If Image 2 has medium or long hair, let side hair fall naturally along the outer shoulder line or behind the shoulders.',
      'Shoulder clearance: Hair may touch the outer shoulder area, but should not drape across the shirt center or over the beer glass.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'No mannequin carry-over: Do NOT leave any mannequin skin or blank texture under the mouth or around the chin.',
      'Single-head rule: Keep only one face aligned to the placeholder neck.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic.',
      'Neck skin tone continuity: Generate the neck with a SINGLE consistent skin tone from chin all the way down to the jersey collar, MATCHING the body skin tone visible at the collar and shoulder area.',
      'Neck depth coverage: Generate realistic neck skin reaching deep into the collar opening area. The AI-generated neck must seamlessly meet the body skin with no exposed transition seam.',
      'Background consistency: Keep the locker background unchanged and blend the outer head edge softly.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'half face', 'cropped crown', 'top-clipped hair', 'clipped hair top',
      'side-clipped hair', 'hair cut off at edge', 'hair touching mask boundary',
      'double face', 'residual mannequin head',
      'invented bangs', 'ponytail from down hair',
      'long hair over center chest', 'hair covering beer glass',
      'blurry neck', 'missing chin', 'blank mannequin neck',
      'dark head hole', 'black face void',
      'literal selfie crop', 'source image patch',
      'neck color seam', 'two-tone neck', 'neck skin tone jump', 'visible neck boundary line',
      'oversized head', 'giant head', 'head filling mask', 'head overflowing replacement area',
      'enlarged head', 'swollen face', 'head too big for frame', 'head touching mask edge',
      'wide head', 'broad face',
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'different hairstyle', 'changed hair texture',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
    ],
    mask: {
      cx: 1140, cy: 846, w: 131, h: 226,
      apiCx: 1142, apiCy: 810, apiW: 110, apiH: 230,
      apiShape: 'hairDome',
      apiDomeH: 128,
      apiDomeExpandX: 12,
      apiSideHairW: 20,
      apiSideHairH: 72,
      apiSideHairOffsetX: 62,
      apiSideHairOffsetY: 122,
      apiNeckRx: 68,
      apiNeckRy: 142,
      apiNeckOffsetY: 200,
      compCx: 1142, compCy: 814, compW: 164, compH: 332,
      compShape: 'hairDome',
      compDomeH: 144,
      compDomeExpandX: 24,
      compSideHairW: 30,
      compSideHairH: 100,
      compSideHairOffsetX: 80,
      compSideHairOffsetY: 138,
      compNeckRx: 104,
      compNeckRy: 184,
      compNeckOffsetY: 218,
      compFeather: 30,
    },
  },
};
