module.exports = {
  male: {
    file: '场景4男.png', label: '场景4男（啤酒节，替换最左）',
    mode: 'faceswap-composite', size: '2560x1536', guidance: 8,
    // faceswap-composite: 先用 faceswap 模式生成完整换脸图，再用 post-composite mask 锁定背景
    strength: 0.65,
    templateType: 'faceswap',
    targetPerson: 'the person on the far left',
    refScale: 0.40, refAnchor: 'north', refOffsetY: 0.08,
    refCrop: { width: 0.78, height: 0.68, offsetX: 0.5, offsetY: 0.02 },
    skipComposite: true, // faceswap prompt 已锁定背景，跳过 post-composite
    validateHeadSwap: false,
    validationTarget: 'the person on the far left',
    validationRule: 'The swapped head must be one complete, realistic human face naturally attached to the body. A dark block, blank patch, or missing head is FAIL. Source-photo clothing copied into the scene is also FAIL.',
    mask: {
      cx: 80, cy: 132, w: 90, h: 138,
      apiCx: 82, apiCy: 126, apiW: 104, apiH: 136,
      compCx: 82, compCy: 128, compW: 134, compH: 164,
      compSolidTopH: 28,
      compSolidTopInset: 12,
      compFeather: 8,
    },
  },
  female: {
    file: '场景4女.png', label: '场景4女（啤酒节，替换最左）',
    mode: 'inpaint', size: '2560x1536', guidance: 10,
    controlProfile: 'scene4_festival',
    refScaleCandidates: [0.30, 0.36], refAnchor: 'north', refOffsetY: 0.08,
    refCrop: { width: 0.72, height: 0.56, offsetX: 0.5, offsetY: 0.04 },
    validateHeadSwap: false,
    validationTarget: 'the person on the far left',
    validationRule: 'The swapped person must keep the original outfit from Image 1. Source-photo clothing is FAIL.',
    extraPromptLines: [
      'Festival portrait fit: Keep the inserted female head compact, upright, and centered above the neck in the group photo.',
      'Female head scale: Keep the female head modest and proportional. Do NOT enlarge the face to fill the whole replacement box.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis.',
      'Crown clearance: Leave visible breathing room above the crown for the full hair silhouette.',
      'Long-hair routing: If Image 2 has long hair, let side hair fall naturally behind the shoulders and onto the upper back.',
      'Scene clothing preservation: Keep the original outfit from Image 1. Do NOT replace with clothing from Image 2.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'Single-head rule: Keep only one face aligned to the placeholder neck.',
    ],
    extraNegativeTerms: [
      'missing chin', 'blank mannequin neck',
      'double face', 'residual mannequin head',
      'oversized head', 'cropped crown',
      'short bob from long-haired source',
      'source photo background',
    ],
    mask: {
      cx: 84, cy: 98, w: 84, h: 132,
      apiCx: 84, apiCy: 94, apiW: 90, apiH: 132,
      compCx: 84, compCy: 96, compW: 118, compH: 164,
      compSolidTopH: 22,
      compSolidTopInset: 12,
      compFeather: 8,
    },
  },
};
