module.exports = {
  male: {
    file: '场景3.jpg', label: '场景3（通道举9号球衣）',
    mode: 'inpaint', size: '2560x1536', guidance: 10,
    refScale: 0.36, refAnchor: 'north', refOffsetY: 0.05,
    refSoftOvalOnFlatBackground: true,
    extraPromptLines: [
      'Tunnel portrait fit: Keep the inserted head compact, upright, and centered above the neck opening behind the jersey.',
      'Head size lock: Keep the final head slightly smaller than the full replacement box so the full crown, temples, cheeks, jawline, and chin fit naturally.',
      'Template size lock: Match the mannequin head size in Image 1. Keep the widest part of the head clearly narrower than the shoulder span, never close to shoulder-to-shoulder width.',
      'Proportion lock: Keep a natural head-to-shoulder ratio. Do NOT create a bobblehead look or make the head dominate the upper body.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis. Do NOT slide the head left, right, or downward.',
      'Vertical lock: Keep the eyes in the upper-middle of the replacement area and keep the chin clearly above the top edge of the jersey.',
      'Neck seat lock: Seat the jaw and neck naturally into the collar opening. Do NOT leave the head floating high above the shoulders or detached from the neck base.',
      'Crown clearance: Leave visible breathing room above the crown. Do NOT let the top hair press against or clip into the top edge of the replacement area.',
      'Patch suppression: The replacement area must contain only the head, hair, ears, and natural neck transition. Do NOT expose any source-photo wall, ceiling, room corner, window frame, or rectangular background patch.',
      'Background lock: Do NOT bring any source-photo wall, ID-photo backdrop, or indoor background into Image 1.',
    ],
    extraNegativeTerms: [
      'oversized head', 'giant face', 'large head small body', 'zoomed-in face', 'bobblehead proportions',
      'head as wide as shoulders', 'shoulder-width head', 'floating head', 'detached neck',
      'off-center head', 'shifted head', 'head too low', 'head too high',
      'cropped crown', 'top-clipped hair', 'cut-off forehead',
      'face inside jersey', 'chin inside jersey', 'portrait sunk too low',
      'source photo corner', 'room corner patch', 'ceiling patch', 'window frame patch',
      'source photo background', 'id photo background', 'indoor wall patch',
      'visible square crop edge', 'rectangular patch edge',
      'cartoon avatar', '3d avatar', 'emoji face', 'pixar face', 'game character face', 'stylized portrait',
    ],
    mask: {
      cx: 934, cy: 288, w: 214, h: 382,
      apiCx: 934, apiCy: 270, apiW: 190, apiH: 350,
      compCx: 934, compCy: 274, compW: 236, compH: 394,
      compSolidTopH: 136,
      compSolidTopInset: 14,
      compFeather: 12,
    },
  },
  female: {
    file: '场景3.jpg', label: '场景3（通道举9号球衣）',
    mode: 'inpaint', size: '2560x1536', guidance: 10,
    refScale: 0.28, refAnchor: 'north', refOffsetY: 0.04,
    refCrop: { width: 0.72, height: 0.88, offsetX: 0.5, anchor: 'north', offsetY: 0.0 },
    refAlwaysSoftOval: true,
    refSoftOvalOnFlatBackground: true,
    extraPromptLines: [
      'Tunnel portrait fit: Keep the inserted female head compact, upright, and centered above the neck opening behind the jersey.',
      'Female head scale: Keep the female head modest and slightly smaller than the placeholder width.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis. Do NOT slide the head left or right.',
      'Vertical lock: Keep the eyes in the upper-middle and keep the chin clearly above the jersey edge.',
      'Crown clearance: Leave visible breathing room above the crown for the full hair silhouette.',
      'Hairstyle source lock: Reproduce the hairstyle from Image 2, including parting, fringe status, and whether hair is worn down or tied up.',
      'Long-hair routing: If Image 2 has medium or long hair, let side hair fall naturally along the neck and behind the shoulders.',
      'Full-head completion: Output one complete photorealistic head from crown to chin. Do NOT output only a cropped slice from Image 2.',
      'Patch suppression: The replacement area must contain only head, hair, ears, and natural neck transition.',
      'Background lock: Do NOT bring any source-photo background into Image 1.',
    ],
    extraNegativeTerms: [
      'oversized female head', 'bobblehead proportions',
      'cropped crown', 'top-clipped hair',
      'face inside jersey', 'chin inside jersey',
      'literal selfie crop', 'source image patch',
      'stiff side hair strip', 'hair over chest logo area',
      'cartoon avatar', '3d avatar',
      'long hair over front jersey', 'hair across chest',
    ],
    mask: {
      cx: 934, cy: 284, w: 202, h: 374,
      apiCx: 934, apiCy: 260, apiW: 194, apiH: 360,
      apiShape: 'hairDome',
      apiDomeH: 100,
      apiDomeExpandX: 12,
      apiSideHairW: 20,
      apiSideHairH: 68,
      apiSideHairOffsetX: 90,
      apiSideHairOffsetY: 164,
      compCx: 934, compCy: 264, compW: 236, compH: 404,
      compShape: 'hairDome',
      compDomeH: 108,
      compDomeExpandX: 14,
      compSideHairW: 24,
      compSideHairH: 84,
      compSideHairOffsetX: 98,
      compSideHairOffsetY: 174,
      compFeather: 12,
    },
  },
};
