// Scene 3 config: inpaint mode with hairDome mask for both male and female
// v1.6: Added lower-body taper support for hairDome masks and lifted Scene3 female
//   head placement so the chin no longer sits on the jersey collar.
//   Female config now uses a narrower lower mask, slightly smaller normalized head,
//   and stronger visible-neck guidance.
module.exports = {
  male: {
    file: '场景3.jpg', label: '场景3（通道举9号球衣）',
    mode: 'inpaint', size: '2560x1536', guidance: 10,
    refScale: 0.42, refAnchor: 'north', refOffsetY: 0.05,
    refNormalize: true,
    refSoftOvalOnFlatBackground: true,
    validateHeadSwap: true,
    validationTarget: 'the main swapped person holding the jersey',
    validationRule: 'The head must be complete from crown to chin above the jersey. No face inside the jersey. The neck must transition naturally above the collar while keeping the original red collar ring visible.',
    extraPromptLines: [
      'Tunnel portrait fit: Keep the inserted head compact, upright, and centered above the neck opening behind the jersey.',
      'Head size lock: Keep the final head slightly smaller than the full replacement box so the full crown, temples, cheeks, jawline, and chin fit naturally.',
      'Template size lock: Match the mannequin head size in Image 1. Keep the widest part of the head clearly narrower than the shoulder span.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis. Do NOT slide the head left, right, or downward.',
      'Vertical lock: Keep the eyes in the upper-middle of the replacement area and keep the chin clearly above the top edge of the jersey.',
      'Neck seat lock: Seat the jaw and neck naturally into the collar opening. Do NOT leave the head floating high above the shoulders.',
      'Crown clearance: Leave visible breathing room above the crown. Do NOT let the top hair clip into the top edge of the replacement area.',
      'Hairstyle source lock: Reproduce the EXACT hairstyle from Image 2 — same length, same texture, same volume, same parting direction. Do NOT invent or change the hairstyle.',
      'Short-hair fidelity: If Image 2 shows very short hair (buzz cut, crew cut, fade), the result MUST also show very short hair. Do NOT add length or volume.',
      'Bang rule: If Image 2 shows no bangs, do NOT invent bangs or curtain fringe.',
      'Hair state lock: If Image 2 shows the hair worn down, keep it worn down. Do NOT convert loose hair into a bun, ponytail, or tied-up updo.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'Full-head completion: Generate one complete photorealistic head from crown to chin with a natural neck. Do NOT leave a dark block or blank patch.',
      'Skin tone continuity: The skin tone of the face and neck must smoothly match the body skin tone at the shoulder boundary. No visible color jump or seam.',
      'Collar preservation: Keep the original red collar ring and neckline seam from Image 1 exactly visible and unchanged.',
      'Neck stop line: The generated neck must end above the jersey collar seam. Do NOT paint skin over the collar, chest panel, or neckline border.',
      'Shoulder integrity: Keep the original shoulder line and jersey collar from Image 1 exactly as-is. No ghost shoulder, no duplicate shoulder edge, no extra fabric layer, no missing shoulder area.',
      'Close-selfie handling: If Image 2 is a close selfie, infer one complete natural head from visible cues only. Do NOT paste a literal selfie rectangle.',
      'Patch suppression: The replacement area must contain only the head, hair, ears, and natural neck transition. Do NOT expose any source-photo wall, ceiling, or rectangular background patch.',
      'Background lock: Do NOT bring any source-photo background into Image 1.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'oversized head', 'giant face', 'large head small body', 'zoomed-in face', 'bobblehead proportions',
      'head as wide as shoulders', 'shoulder-width head', 'floating head', 'detached neck',
      'off-center head', 'shifted head', 'head too low', 'head too high',
      'cropped crown', 'top-clipped hair', 'cut-off forehead',
      'missing chin', 'melted lower face', 'blank mannequin neck', 'unfinished jawline',
      'face inside jersey', 'chin inside jersey', 'portrait sunk too low',
      'dark head hole', 'black face void',
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'different hairstyle', 'changed hair texture',
      'invented bangs', 'curtain bangs not in source',
      'bob cut from short hair', 'long hair from buzz cut',
      'tied-up hair from loose-hair source', 'ponytail from down hair',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
      'source photo corner', 'room corner patch', 'ceiling patch', 'window frame patch',
      'source photo background', 'id photo background', 'indoor wall patch',
      'visible square crop edge', 'rectangular patch edge',
      'literal selfie crop', 'source image patch',
      'two-tone neck', 'neck color seam', 'neck color boundary', 'split neck color',
      'erased collar', 'missing neckline seam', 'skin over jersey collar', 'covered red collar ring',
      'ghost shoulder', 'duplicate shoulder', 'double shoulder line', 'extra shoulder layer',
      'missing shoulder', 'erased shoulder', 'shoulder gap',
    ],
    mask: {
      cx: 934, cy: 280, w: 214, h: 394,
      apiCx: 934, apiCy: 254, apiW: 196, apiH: 358,
      apiShape: 'hairDome',
      apiDomeH: 138,
      apiDomeExpandX: 16,
      apiSideHairW: 22,
      apiSideHairH: 70,
      apiSideHairOffsetX: 88,
      apiSideHairOffsetY: 152,
      // Neck ellipse: center at body bottom (apiTop+apiH=433), extends below into collar zone
      // apiTop=75, apiH=358 → bodyBottom=433. neckCy=433, ry=22 → covers 411-455
      apiNeckRx: 44,
      apiNeckRy: 22,
      apiNeckOffsetY: 358,
      apiMaxBottomY: 452,
      compCx: 934, compCy: 258, compW: 240, compH: 392,
      compShape: 'hairDome',
      compDomeH: 148,
      compDomeExpandX: 18,
      compSideHairW: 26,
      compSideHairH: 86,
      compSideHairOffsetX: 96,
      compSideHairOffsetY: 164,
      // Comp neck: compTop=62, compH=392 → bodyBottom=454. neckCy=454, ry=24 → covers 430-478
      compNeckRx: 52,
      compNeckRy: 24,
      compNeckOffsetY: 392,
      compMaxBottomY: 470,
      compFeather: 14,
    },
  },
  female: {
    file: '场景3.jpg', label: '场景3（通道举9号球衣）',
    mode: 'inpaint', size: '2560x1536', guidance: 10,
    refScale: 0.26, refAnchor: 'north', refOffsetY: 0.04,
    refCrop: { width: 0.72, height: 0.88, offsetX: 0.5, anchor: 'north', offsetY: 0.0 },
    refNormalize: true,
    refNormalizeMaxCropWidth: 0.78,
    refNormalizeMaxCropHeight: 0.72,
    // Keep the normalized female head a bit smaller so Scene3 leaves visible neck room.
    refHeadFillRatio: 0.26,
    refAlwaysSoftOval: true,
    refSoftOvalOnFlatBackground: true,
    validateHeadSwap: true,
    validationTarget: 'the main swapped person holding the jersey',
    validationRule: 'The female head must be compact with full hairstyle visible. No face inside the jersey. Natural skin tone continuity. The original red collar ring must remain visible.',
    extraPromptLines: [
      'Tunnel portrait fit: Keep the inserted female head compact, upright, and centered above the neck opening behind the jersey.',
      'Female head scale: Keep the female head modest and slightly smaller than the placeholder width.',
      'Center lock: Keep the nose and mouth aligned to the original neck axis. Do NOT slide the head left or right.',
      'Vertical lock: Keep the eyes in the upper-middle and keep the chin clearly above the jersey edge.',
      'Visible neck lock: Leave a clearly visible front neck section between the chin and the jersey collar. Do NOT let the chin rest directly on the collar.',
      'Head height lock: Place the female head slightly higher inside the replacement area so the jawline ends above the collar opening.',
      'Crown clearance: Leave visible breathing room above the crown for the full hair silhouette.',
      'Hairstyle source lock: Reproduce the exact hairstyle structure from Image 2, including parting direction, fringe status, top-hair volume, and whether the hair is worn down or tied up.',
      'Bang rule: If Image 2 shows an exposed forehead or no bangs, do NOT invent bangs, curtain fringe, or a new front fringe.',
      'Hair state lock: If Image 2 shows the hair worn down, keep it worn down. Do NOT convert loose hair into a bun, ponytail, tied-up updo, or a generic celebrity-style hairstyle.',
      'Long-hair routing: If Image 2 has medium or long hair, let side hair fall naturally along the neck and behind the shoulders.',
      'Close-selfie handling: If Image 2 is a close selfie or partially framed photo, infer one complete natural head from the visible identity cues only. Do NOT paste a literal photo crop, room patch, or selfie rectangle into Image 1.',
      'Full-head completion: Even when Image 2 is tightly framed, output one complete photorealistic head from crown to chin above the jersey. Do NOT output only the upper half of the source face.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'Skin tone continuity: The skin tone of the face and neck must smoothly match the body skin tone at the shoulder boundary. No visible color jump or seam.',
      'Collar preservation: Keep the original red collar ring and neckline seam from Image 1 exactly visible and unchanged.',
      'Neck stop line: The generated neck must end above the jersey collar seam. Do NOT paint skin over the collar, chest panel, or neckline border.',
      'Shoulder integrity: Keep the original shoulder line and jersey collar from Image 1 exactly as-is. No ghost shoulder, no duplicate shoulder edge, no extra fabric layer, no missing shoulder area.',
      'Patch suppression: The replacement area must contain only head, hair, ears, and natural neck transition.',
      'Background lock: Do NOT bring any source-photo background into Image 1.',
      'Realism lock: The face must remain a real photographic human face with natural skin texture. No cartoon, no CGI, no doll-like stylization, no oversized eyes, no plastic skin.',
    ],
    extraNegativeTerms: [
      'oversized female head', 'bobblehead proportions',
      'no visible neck', 'stump neck', 'chin glued to collar', 'jaw fused to collar', 'chin resting on jersey',
      'cropped crown', 'top-clipped hair',
      'missing chin', 'melted lower face', 'blank mannequin neck',
      'face inside jersey', 'chin inside jersey',
      'literal selfie crop', 'source image patch', 'partial selfie patch',
      'invented bangs', 'added fringe', 'curtain bangs not in source', 'generic idol fringe',
      'tied-up hair from loose-hair source', 'ponytail from down hair', 'bun from loose hair',
      'invented hairstyle', 'added hair length', 'extra hair volume',
      'different hairstyle', 'changed hair texture',
      'stiff side hair strip', 'hair over chest logo area',
      'dark head hole', 'black face void',
      'source photo background', 'indoor wall patch', 'room corner patch', 'ceiling patch',
      'cartoon face', 'cartoon avatar', 'anime face', 'cgi face', '3d avatar',
      'pixar face', 'emoji face', 'doll face', 'toy face', 'oversized eyes',
      'plastic skin', '3d render face',
      'long hair over front jersey', 'hair across chest',
      'two-tone neck', 'neck color seam', 'neck color boundary', 'split neck color',
      'erased collar', 'missing neckline seam', 'skin over jersey collar', 'covered red collar ring',
      'ghost shoulder', 'duplicate shoulder', 'double shoulder line', 'extra shoulder layer',
      'missing shoulder', 'erased shoulder', 'shoulder gap',
    ],
    mask: {
      cx: 934, cy: 292, w: 192, h: 350,
      apiCx: 934, apiCy: 260, apiW: 184, apiH: 340,
      apiShape: 'hairDome',
      apiDomeH: 96,
      apiDomeExpandX: 12,
      apiSideHairW: 22,
      apiSideHairH: 72,
      apiSideHairOffsetX: 88,
      apiSideHairOffsetY: 158,
      apiBodyInsetX: 12,
      // Neck ellipse: keep a narrow neck bridge without repainting the whole collar zone.
      apiNeckRx: 34,
      apiNeckRy: 24,
      apiNeckOffsetY: 340,
      apiMaxBottomY: 458,
      compCx: 934, compCy: 264, compW: 224, compH: 376,
      compShape: 'hairDome',
      compDomeH: 104,
      compDomeExpandX: 14,
      compSideHairW: 26,
      compSideHairH: 88,
      compSideHairOffsetX: 96,
      compSideHairOffsetY: 174,
      compBodyInsetX: 18,
      // Composite mask keeps more neck height while tapering toward the collar opening.
      compNeckRx: 40,
      compNeckRy: 28,
      compNeckOffsetY: 376,
      compMaxBottomY: 476,
      compFeather: 14,
    },
  },
};
