module.exports = {
  male: {
    file: '场景1男.jpg', label: '场景1男（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    controlProfile: 'scene1_portrait',
    refScale: 0.34, refAnchor: 'north', refOffsetY: 0.14,
    extraPromptLines: [
      'Head swap framing: Replace the whole mannequin head area, including crown, forehead, cheeks, mouth, jawline, and chin.',
      'Replacement coverage: The rectangular head-swap region must fully cover the entire user head content that needs replacement, not just the center face area.',
      'Neck blend: Keep a natural transition from the lower jaw into the neck opening above the jersey collar.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic, not blurry, foggy, or airbrushed.',
      'Size reference: Keep the final head close to the original player head size, not larger.',
      'Background consistency: Keep the locker background color unchanged and blend the outer head edge softly into the original background.',
    ],
    extraNegativeTerms: [
      'face texture on jersey', 'facial features on torso', 'eyes on clothing', 'mouth on shirt', 'hair on chest',
      'half face', 'side-clipped face', 'cropped forehead', 'cropped chin',
      'dark head hole', 'black face void',
      'blurry neck', 'foggy neck edge', 'airbrushed neck', 'mushy jawline',
      'cartoon face', 'anime face', 'cgi face', 'doll face', 'oversized eyes',
    ],
    mask: {
      cx: 1140, cy: 844, w: 168, h: 276,
      apiCx: 1142, apiCy: 840, apiW: 176, apiH: 286,
      compCx: 1142, compCy: 844, compW: 194, compH: 308,
      compSolidTopH: 112,
      compSolidTopInset: 16,
      compFeather: 8,
    },
  },
  female: {
    file: '场景1女.jpg', label: '场景1女（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    controlProfile: 'scene1_portrait',
    refScale: 0.32, refAnchor: 'north', refOffsetY: 0.14,
    extraPromptLines: [
      'Head swap framing: Replace the whole mannequin head area, including crown, forehead, cheeks, mouth, jawline, and chin.',
      'Replacement coverage: The rectangular head-swap region must fully cover the entire user head content that needs replacement, not just the center face area.',
      'Neck blend: Keep a natural transition from the lower jaw into the neck opening above the jersey collar.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic, not blurry, foggy, or airbrushed.',
      'Size reference: Keep the final head close to the original player head size, not larger.',
      'Background consistency: Keep the locker background color unchanged and blend the outer head edge softly into the original background.',
    ],
    extraNegativeTerms: [
      'face texture on jersey', 'facial features on torso', 'eyes on clothing', 'mouth on shirt', 'hair on chest',
      'half face', 'side-clipped face', 'cropped forehead', 'cropped chin',
      'dark head hole', 'black face void',
      'blurry neck', 'foggy neck edge', 'airbrushed neck', 'mushy jawline',
      'cartoon face', 'anime face', 'cgi face', 'doll face', 'oversized eyes',
    ],
    mask: {
      cx: 1140, cy: 846, w: 164, h: 282,
      apiCx: 1142, apiCy: 840, apiW: 174, apiH: 292,
      compCx: 1142, compCy: 844, compW: 192, compH: 314,
      compSolidTopH: 116,
      compSolidTopInset: 16,
      compFeather: 8,
    },
  },
};
