module.exports = {
  male: {
    file: '场景1男.jpg', label: '场景1男（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    controlProfile: 'scene1_portrait',
    refScale: 0.38, refAnchor: 'north', refOffsetY: 0.10,
    refScaleCandidates: [0.38, 0.48],
    includeOriginalReferenceFallback: true,
    validateHeadSwap: true,
    extraPromptLines: [
      'Head swap framing: Replace the whole mannequin head area, including crown, forehead, cheeks, mouth, jawline, and chin.',
      'Compact portrait fit: Keep the inserted head compact and upright, slightly smaller than the full replacement box so the full crown and jawline stay visible.',
      'Replacement coverage: The head-swap region must fully cover the entire user head content that needs replacement, not just the center face area.',
      'Center lock: Keep the whole face centered inside the replacement area. Do not output only half a face or shift the head to one side.',
      'Vertical lock: Keep the eyes in the upper-middle of the replacement area and keep the chin clearly above the jersey collar and beer glass area.',
      'Crown clearance: Leave visible breathing room above the crown. Do NOT let the top hair press against or clip into the top edge of the replacement area.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'No mannequin carry-over: Do NOT leave any mannequin skin, blank mannequin texture, or melted placeholder surface around the chin or neck base.',
      'Hair edge quality: Keep the hairline and outer hair edges clean and natural, with no dark halo, black fringe, or muddy edge glow.',
      'Neck blend: Keep a natural transition from the lower jaw into the neck opening above the jersey collar.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic, not blurry, foggy, or airbrushed.',
      'Lower coverage: Extend the head-swap result low enough to fully replace the original neck base and hide any leftover source collar or neckline.',
      'Size reference: Keep the final head close to the original player head size, not larger.',
      'Single-head rule: Keep only one face aligned to the placeholder neck. No adjacent second face and no leftover mannequin silhouette.',
      'Patch suppression: The replacement area must contain only the head, hair, ears, and natural neck transition. Do NOT expose any source-photo wall, ceiling, room corner, or rectangular background patch.',
      'Background consistency: Keep the locker background color unchanged and blend the outer head edge softly into the original background.',
      'Failure prevention: Even if Image 2 is tightly framed or difficult, you must still generate one complete realistic human head from Image 2. Never leave an empty neck stump, dark void, black block, or plain background patch where the head should be.',
    ],
    extraNegativeTerms: [
      'face texture on jersey', 'facial features on torso', 'eyes on clothing', 'mouth on shirt', 'hair on chest',
      'half face', 'side-clipped face', 'cropped forehead', 'cropped chin',
      'double face', 'duplicate face', 'adjacent face', 'offset face', 'residual mannequin head',
      'oversized head', 'zoomed-in face', 'head too low', 'head too high',
      'cropped crown', 'top-clipped hair', 'cut-off forehead',
      'missing chin', 'melted lower face', 'blank mannequin neck', 'unfinished jawline',
      'dark halo around hair', 'black fringe around hairline', 'muddy hair edge',
      'dark head hole', 'black face void',
      'blank blue patch', 'background block', 'half replaced face',
      'jersey patch in face area', 'torso patch as head',
      'source photo corner', 'room corner patch', 'ceiling patch',
      'blurry neck', 'foggy neck edge', 'airbrushed neck', 'mushy jawline',
      'missing head', 'no head', 'empty neck stump', 'neck stump', 'blank head area', 'background patch instead of head',
      'cartoon face', 'anime face', 'cgi face', 'doll face', 'oversized eyes',
    ],
    mask: {
      cx: 1140, cy: 844, w: 170, h: 286,
      apiCx: 1142, apiCy: 838, apiW: 176, apiH: 300,
      apiShape: 'hairDome',
      apiDomeH: 100,
      apiDomeExpandX: 14,
      apiSideHairW: 20,
      apiSideHairH: 58,
      apiSideHairOffsetX: 82,
      apiSideHairOffsetY: 146,
      compCx: 1142, compCy: 844, compW: 196, compH: 320,
      compShape: 'hairDome',
      compDomeH: 110,
      compDomeExpandX: 18,
      compSideHairW: 26,
      compSideHairH: 72,
      compSideHairOffsetX: 88,
      compSideHairOffsetY: 156,
      compFeather: 10,
    },
  },
  female: {
    file: '场景1女.jpg', label: '场景1女（更衣室）',
    mode: 'inpaint', size: '2048x2560', guidance: 10,
    controlProfile: 'scene1_portrait',
    refScale: 0.30, refAnchor: 'north', refOffsetY: 0.10,
    refScaleCandidates: [0.26, 0.30, 0.36],
    refAlwaysSoftOval: true,
    extraPromptLines: [
      'Head swap framing: Replace the whole mannequin head area, including crown, forehead, cheeks, mouth, jawline, and chin.',
      'Compact portrait fit: Keep the inserted female head compact and upright, slightly smaller than the full replacement box so the full crown, temples, cheeks, jawline, and chin stay visible.',
      'Replacement coverage: The head-swap region must fully cover the entire user head content that needs replacement, not just the center face area.',
      'Center lock: Keep the whole face centered inside the replacement area. Do not output only half a face or shift the head to one side.',
      'Vertical lock: Keep the eyes in the upper-middle of the replacement area and keep the chin clearly above the jersey collar and beer glass area.',
      'Crown clearance: Leave visible breathing room above the crown so the full hair silhouette stays inside the replacement area.',
      'Hairstyle source lock: Reproduce the exact hairstyle structure from Image 2, including parting direction, fringe or no-fringe status, top-hair volume, and whether the hair is worn down or tied up.',
      'Bang rule: If Image 2 shows an exposed forehead or no bangs, do NOT invent bangs, curtain fringe, or a new front fringe.',
      'Hair state lock: If Image 2 shows the hair worn down, keep it worn down. Do NOT convert loose hair into a bun, ponytail, tied-up updo, or a generic celebrity-style hairstyle.',
      'Close-selfie handling: If Image 2 is a close selfie or tightly framed photo, infer one complete natural head from the visible face and hair cues only. Do NOT paste a literal lower-face crop, neck crop, or selfie rectangle into Image 1.',
      'Reference isolation: Use ONLY the face, hair, ears, and natural neck identity from Image 2. Do NOT copy headphones, earphones, hats, collars, hoodies, shoulders, hands, or any source-photo accessories into Image 1.',
      'Hair edge quality: Keep the hairline and outer hair edges clean and natural, with no dark halo, black fringe, or muddy edge glow.',
      'Hair silhouette: Keep a rounded crown and natural outer hair contour, not a flat-topped or box-shaped head.',
      'Side coverage: Keep both ears and the outer side-hair contour inside the replacement area. Do NOT trim the side hair at the left or right edge.',
      'Long-hair routing: If Image 2 has medium or long hair, let the longer side hair continue beside the face and then fall naturally along the OUTER shoulder line or behind the shoulders.',
      'Long-hair priority: Route most of the hair mass to the outer shoulders and back, not toward the center chest.',
      'Shoulder clearance: Keep the center neckline, upper chest, and the front face of the beer glass unobstructed. Hair may touch the outer shoulder area, but should not drape across the shirt center or over the glass.',
      'Lower side hair: Preserve the side hair below the jawline down toward the outer shoulder line, with a soft natural taper instead of a stiff cut-off edge.',
      'Jaw completion: Fully generate the lower face, including nose base, lips, chin, jawline, and the front of the neck.',
      'No mannequin carry-over: Do NOT leave any mannequin skin, blank mannequin texture, or melted placeholder surface under the mouth or around the chin.',
      'Neck blend: Keep a natural transition from the lower jaw into the neck opening above the jersey collar.',
      'Neck base coverage: Extend the replacement low enough to fully cover the throat and neck base down into the collar opening so no cut line remains at the neck seam.',
      'Neck edge clarity: Keep the jaw-to-neck and neck-to-collar transition clean and realistic, not blurry, foggy, or airbrushed.',
      'Collar blend: The lower neck must dissolve smoothly into the original collar opening and upper shoulder area, with no straight horizontal cut line across the neck.',
      'Seam suppression: Do NOT leave a pasted edge, hard cut line, rectangular join, or visible splice around the neck base or collar opening.',
      'Size reference: Keep the final head close to the original player head size, not larger.',
      'Single-head rule: Keep only one face aligned to the placeholder neck. No adjacent second face and no leftover mannequin silhouette.',
      'Patch suppression: The replacement area must contain only the head, hair, ears, and natural neck transition. Do NOT expose any source-photo wall, ceiling, room corner, or rectangular background patch.',
      'Background consistency: Keep the locker background color unchanged and blend the outer head edge softly into the original background.',
    ],
    extraNegativeTerms: [
      'face texture on jersey', 'facial features on torso', 'eyes on clothing', 'mouth on shirt', 'hair on chest',
      'half face', 'side-clipped face', 'cropped forehead', 'cropped chin',
      'double face', 'duplicate face', 'adjacent face', 'offset face', 'residual mannequin head',
      'oversized female head', 'zoomed-in face', 'head too low', 'head too high',
      'cropped crown', 'top-clipped hair', 'cut-off forehead',
      'invented bangs', 'added fringe', 'curtain bangs not in source', 'generic idol fringe',
      'tied-up hair from loose-hair source', 'ponytail from down hair', 'bun from loose hair', 'updo not in source',
      'headphones', 'earphones', 'headset around neck', 'neck accessory from source photo', 'source hoodie collar', 'source shoulders', 'source clothing patch',
      'missing ear', 'cropped ear', 'trimmed side hair', 'hair cut off at edge',
      'dark halo around hair', 'black fringe around hairline', 'muddy hair edge',
      'short bob from long-haired source', 'jaw-length bob', 'shoulder-cropped hair', 'hair ending in mid-air', 'floating wig edge',
      'long hair over center chest', 'hair across center chest', 'hair covering beer glass', 'hair covering shirt collar center', 'front-draped hair curtain',
      'flat hair curtain', 'helmet hair', 'wig shell', 'stiff side hair panel', 'hard cut-off hair edge',
      'hair ending at jawline', 'hair ending at neck base', 'abrupt hair stop at shoulder',
      'missing chin', 'melted lower face', 'blank mannequin neck', 'placeholder skin', 'unfinished jawline',
      'dark head hole', 'black face void',
      'source photo corner', 'room corner patch', 'ceiling patch', 'literal selfie crop', 'photo rectangle pasted into scene', 'source image patch',
      'blurry neck', 'foggy neck edge', 'airbrushed neck', 'mushy jawline',
      'neck cut line', 'pasted neck edge', 'hard seam at collar', 'floating head', 'rectangular splice at neck', 'horizontal cut line across neck', 'straight shoulder seam under neck',
      'cartoon face', 'anime face', 'cgi face', 'doll face', 'oversized eyes',
    ],
    mask: {
      cx: 1140, cy: 846, w: 164, h: 282,
      apiCx: 1142, apiCy: 838, apiW: 176, apiH: 296,
      apiShape: 'hairDome',
      apiDomeH: 112,
      apiDomeExpandX: 18,
      apiSideHairW: 30,
      apiSideHairH: 92,
      apiSideHairOffsetX: 92,
      apiSideHairOffsetY: 156,
      compCx: 1142, compCy: 848, compW: 200, compH: 334,
      compShape: 'hairDome',
      compDomeH: 118,
      compDomeExpandX: 20,
      compSideHairW: 36,
      compSideHairH: 118,
      compSideHairOffsetX: 100,
      compSideHairOffsetY: 172,
      compFeather: 11,
    },
  },
};
